version: '3.8'

services:
  backend:
    build:
      context: ./backend-django/backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env 
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: myprojectdatabases
      MYSQL_USER: user1
      MYSQL_PASSWORD: White450602
      MYSQL_ROOT_PASSWORD: rootpassword

    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  client:
    build:
      context: ./myflutterproject
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5554:5554"
      - "5555:5555"
    volumes:
      - ./myflutterproject:/app
    networks:
      - mynetwork
    environment:
      ANDROID_HOME: /opt/android-sdk
      PATH: /opt/android-sdk/tools:/opt/android-sdk/tools/bin:/opt/android-sdk/platform-tools:$PATH
    stdin_open: true
    tty: true


networks:
  mynetwork:

volumes:
  db_data:
